### ISSUE TITLE
[build] Cache maven artefacts in GitHub Actions

### ISSUE THREAD

**Issue by javahippie** [operaton/operaton#75]
**Is your feature request related to a problem? Please describe.**
We should cache the Maven artefacts in the GitHub Actions build to take load off the Sonatype repo and speed up our builds

**Describe the solution you'd like**
We should enable the cache similar to the way we enabled the SonarQube cache:
```
  - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
```
